spring.application.name=devforge-ai

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

openrouter.api.key=${OPENROUTER_API_KEY} 

openrouter.url=https://openrouter.ai/api/v1/chat/completions

openrouter.model=openrouter/free